language: node_js
node_js: 
  - 14


jobs:
  include:
    script:
        - npm t

notifications:
  slack:
    secure: Z+dHU92m0tUO+HbnupQqytCexZ00kEr1mQLVEIAzcrXfLrQCLXaoIYp3bJ8gc5v0RcwuL5TfJ82kUeuh75oLndto3INIeDnv3dj/rzi90wRLTA0Zn0S6kITXIMk8E4El/TiKMjhq18q+1ektVyJOr51fNgFkvVVMAnBm2Rw0QXgIJaD9fOXNQcor6m1KvgGMgYSKUGa+NVyHe/UwTaw/14BOLtgX6fr7Vchl1uoJ9iOuzbVtcGErFs1NSGYRDiucY5AKUwIsvVFF7tfoVHug1PL6QmmbZtGEyFCTPPY6GnkcoWgixcJl+ulhMldLDaVa9R4a55VzNJzGSHuOs4+wm0C0I9IdbShqI3WlxUVraEvlASSlQqu416RXB8IcDFkHg3Gp0nbexzcjLuh9PSq7ms93StoXip7HRizWPaxwi1ubbMHfaayhgL+Jy2F2Rm2IPcd4fL4d5tWgxzLwatLWmYhzDm5aXVmom9DRQ57+EwEGO0emqlVPDEuVX25WwRY4A0TcW/Q6xzCQ7ecKJqJR4uEd60gfUzMDZhojkXXks74xdT10o1fOJjsxFz4o1H2HadE7GGMgUu3swFZFCkR7lhMXWGgDqOkTywcvJcphQQdvgSrTKtqA5zKFxvhCPaM18kB/akKX9xiWLCAmLXBrvW4X9eJbADIGRIiwx5OyHfA=
